export { default as MostPopular } from "../components/MostPopular";
export { default as Veggie } from "../components/Veggies";
export { default as Desserts } from "../components/Desserts";
export { default as Category } from "../components/Category";
export { default as SearchBar } from "../components/SearchBar";
export { default as Cuisine } from "./Cuisine";
export { default as Recipe } from "./Recipe";
export { default as Searched } from "./Searched";
export { default as Loader } from "../components/Loader/Loader";
